language: ruby
rvm:
- 2.3.0
deploy:
  provider: heroku
  app: sam-and-kitty-dashboard
  api_key:
    secure: BVI0i+AM2fXc+qnWKVi5zBo5EIfoWWgiUZFqCzEQOcZpkL14pnu1DJRytaq925Ox3OlEGiKUwCdlevOOaLk2HeOJGUT7IKqcQTAoqgTvs1MG7NNRlXzk1K9A1RJNpogoRA8wfEMe3zq22y45O2w6uuBHzKWX9mLKLsRYUdxRgeVTKYnbrint1/eWiV7vTelBYQ6ZQGwGJMQCZQHn89pA4WDUxWHdhl+Zpr+itMUqBgYTCJ1kX3kJ1rvUzaY+NdHPN/VHGi8O5XGHwVOmsfNJuA0jkRSFjopeX8zWMOAJ+xJSvxraF8whzdlJleoKbMtU7IMXeZ3nNRloGUIR+jF0BLpKlRsMYTNQOMJ0OxzzJNSBe4sYVkyg5RWJJbKoS3yTWOcV+/HmbKjPCBqi+TNSB4Jzp939r0rJy15F6wOhFXDPklbGOzJVtJoLMgUf+wFpdrxjlhX2eEkVCJDjx1Ibd6vfLSW9VQi8RuARf8RXt6rT6MmrhDyhYnNL3WUsZIrF0qG8HsYOtFkLyOXsxik1RebxbKwOWzqROP0Z01unSfyIxHYjV70bvPsKVR7/DSy5fPPAIePgcJUMFDRVcEMQEnK/P0vv9i2o7M+7WrIsy1AQNlVuCXZMDdgbowzmbtbFA0gA5rO9T5zF8C5B02UMrq5SxKwTcZMEScCzed2CczY=
