catface:
  url: /catface
  title: Catface

snake-data:
  url: /snake
  title: Snake

  datasets:
    length:
#    title: Length Measurement
      type: graph

    weight:
      type: graph

    sheds:
      date-field: Shed completed

    feeds:
      special-fields:
        - Eaten
        - Food
