catface:
  url: /catface
  title: Catface
  repo: pikesley/catface

snake-data:
  url: /snake
  title: Snake
  repo: pikesley/snake-data

  datasets:
    length:
#    title: Length Measurement
      type: graph

    weight:
      type: graph

    sheds:
      date-field: Shed completed

    feeds:
      special-fields:
        - Eaten
        - Food
